# Dockerfile-ClientPython_lab2

FROM python:3.8




VOLUME ["/usr/src/app/auth"]

WORKDIR /usr/src/app

RUN pip install click==8.0.3
RUN pip install confluent-kafka==2.2.0
RUN pip install avro-python3

COPY Lab_2_consumer.py .


ENTRYPOINT ["python3", "Lab_2_consumer.py" ]
