FROM python:3.11-slim-bookworm

COPY requirements.txt .
RUN pip install -r requirements.txt
RUN pip install --upgrade fastavro

WORKDIR /usr/src/app

COPY consumer.py .

ENTRYPOINT ["python3", "consumer.py" ]
