FROM python:3.8

RUN pip install click==8.0.3
RUN pip install confluent-kafka==2.2.0
RUN pip install avro-python3
RUN pip install --upgrade fastavro

RUN pip install signal
RUN pip install io
RUN pip install enum34
RUN pip install asyncio
RUN pip install grpc


WORKDIR /usr/src/app

COPY consumer.py .

VOLUME ["/usr/src/app/auth"]

ENTRYPOINT ["python3", "consumer.py" ]
